name: build
on: workflow_dispatch
jobs:
  build:
    name: Build the image
    runs-on: ubuntu-18.04
    steps:
      - name: "Check out repo"
        uses: actions/checkout@v2
      - name: "Fetch Ediacara"
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.EGF_SSH }}'
          git clone git@github.com:Edinburgh-Genome-Foundry/Ediacara.git
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build Docker image"
        run: |
          docker build . -f containers/Dockerfile \
            -t ghcr.io/edinburgh-genome-foundry/sequeduct:v0.2.3 \
            -t ghcr.io/edinburgh-genome-foundry/sequeduct:latest
      - name: "Release Docker image"
        run: |
          docker push ghcr.io/edinburgh-genome-foundry/sequeduct:v0.2.3
          docker push ghcr.io/edinburgh-genome-foundry/sequeduct:latest
