name: build
on: workflow_dispatch
jobs:
  build:
    name: Build the image
    runs-on: ubuntu-18.04
    steps:
      - name: "Check out repo"
        uses: actions/checkout@v2
      - name: "Fetch Ediacara"
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.EGF_SSH }}'
          git clone git@github.com:Edinburgh-Genome-Foundry/Ediacara.git
      - name: "Build Docker image"
        run: |
          docker build . -f containers/Dockerfile \
            -t ghcr.io/${{ github.repository }}:v0.1.0 \
            -t ghcr.io/${{ github.repository }}:latest
      - name: "Release Docker image"
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/edinburgh-genome-foundry/sequeduct:v0.1.0
          docker push ghcr.io/edinburgh-genome-foundry/sequeduct:latest
